<?php
/**
 * Site audit helper (read-only): "where in the database does this text live?"
 *
 * POST /livecrafts/v1/debug/locate   {post: <id>, texts: ["Heading text", ...]}
 *
 * For every text the editor could NOT link to an ACF field / Elementor setting, this searches the database for
 * that exact text and reports where it is stored, so we know which adapter to build next:
 *   wp_posts (content / title / excerpt)  -> a post-content adapter (Gutenberg, classic editor, WPBakery shortcodes)
 *   wp_postmeta (_elementor_data ...)     -> a builder adapter
 *   wp_options (widgets, site title ...)  -> an options/widget adapter
 *   nav menu items                        -> a menu adapter
 *   nothing found                         -> hard-coded in theme/plugin PHP, generated by JavaScript, or computed
 *
 * It is a diagnostic only: a plain LIKE search can miss text stored JSON-escaped (quotes, accents) - "not found" is a hint,
 * not proof. Capped to 40 texts per call; editors only.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

add_action( 'rest_api_init', function () {
	register_rest_route( 'livecrafts/v1', '/debug/locate', array(
		'methods'             => 'POST',
		'callback'            => 'livecrafts_rest_debug_locate',
		'permission_callback' => 'livecrafts_rest_permission',
	) );
} );

function livecrafts_rest_debug_locate( WP_REST_Request $req ) {
	global $wpdb;
	$post  = (int) $req->get_param( 'post' );
	$texts = $req->get_param( 'texts' );
	if ( $post && ! current_user_can( 'edit_post', $post ) ) return new WP_Error( 'livecrafts_forbidden', 'Not allowed.', array( 'status' => 403 ) );
	if ( ! is_array( $texts ) ) return new WP_Error( 'livecrafts_bad_request', 'texts must be a list.', array( 'status' => 400 ) );

	$clean = array();
	foreach ( $texts as $t ) {
		$t = trim( wp_strip_all_tags( (string) $t ) );
		if ( $t !== '' ) $clean[ $t ] = true;
	}
	$texts = array_slice( array_keys( $clean ), 0, 40 );

	// Navigation menu item titles, loaded once.
	$menu_titles = array();
	foreach ( (array) wp_get_nav_menus() as $menu ) {
		foreach ( (array) wp_get_nav_menu_items( $menu->term_id ) as $item ) {
			$menu_titles[] = array( 'menu' => $menu->name, 'item' => (int) $item->ID, 'title' => $item->title );
		}
	}

	$results = array();
	foreach ( $texts as $text ) {
		$text = (string) $text;
		if ( mb_strlen( $text ) < 3 || mb_strlen( $text ) > 300 ) { $results[ $text ] = array(); continue; }
		$like = '%' . $wpdb->esc_like( $text ) . '%';
		$hits = array();

		// 1) Posts: content / title / excerpt (pages, posts, block templates, template parts, reusable blocks ...)
		$rows = $wpdb->get_results( $wpdb->prepare(
			"SELECT ID, post_type, (post_content LIKE %s) AS in_content, (post_title LIKE %s) AS in_title, (post_excerpt LIKE %s) AS in_excerpt
			 FROM {$wpdb->posts}
			 WHERE post_status NOT IN ('auto-draft','trash') AND post_type <> 'revision'
			   AND ( post_content LIKE %s OR post_title LIKE %s OR post_excerpt LIKE %s ) LIMIT 5",
			$like, $like, $like, $like, $like, $like
		) );
		foreach ( (array) $rows as $r ) {
			$cols = array();
			if ( $r->in_content ) $cols[] = 'post_content';
			if ( $r->in_title )   $cols[] = 'post_title';
			if ( $r->in_excerpt ) $cols[] = 'post_excerpt';
			$hits[] = array( 'where' => 'wp_posts', 'post' => (int) $r->ID, 'post_type' => $r->post_type, 'column' => implode( '+', $cols ) );
		}

		// 2) Post meta (ACF values, Elementor JSON, SEO fields ...)
		$rows = $wpdb->get_results( $wpdb->prepare(
			"SELECT m.post_id, m.meta_key FROM {$wpdb->postmeta} m
			 INNER JOIN {$wpdb->posts} p ON p.ID = m.post_id
			 WHERE m.meta_value LIKE %s AND p.post_type <> 'revision' AND m.meta_key NOT IN ('_edit_lock','_edit_last') LIMIT 5",
			$like
		) );
		foreach ( (array) $rows as $r ) $hits[] = array( 'where' => 'wp_postmeta', 'post' => (int) $r->post_id, 'meta_key' => $r->meta_key );

		// 3) Options (site title, widgets, theme mods, plugin settings) - without caches and our own data
		$rows = $wpdb->get_results( $wpdb->prepare(
			"SELECT option_name FROM {$wpdb->options}
			 WHERE option_value LIKE %s AND option_name NOT LIKE %s AND option_name NOT LIKE %s AND option_name NOT LIKE %s LIMIT 5",
			$like, $wpdb->esc_like( '_transient' ) . '%', $wpdb->esc_like( '_site_transient' ) . '%', $wpdb->esc_like( 'livecrafts_' ) . '%'
		) );
		foreach ( (array) $rows as $r ) $hits[] = array( 'where' => 'wp_options', 'option' => $r->option_name );

		// 4) Menu items
		foreach ( $menu_titles as $mt ) {
			if ( strcasecmp( trim( $mt['title'] ), $text ) === 0 ) $hits[] = array( 'where' => 'nav_menu_item', 'menu' => $mt['menu'], 'item' => $mt['item'] );
		}

		$results[ $text ] = $hits;
	}

	return array(
		'results' => $results,
		'note'    => 'Plain LIKE search: text stored JSON-escaped (quotes, accents, emoji) can be missed. "No hits" suggests hard-coded theme/plugin text, JavaScript-generated text, or a computed value.',
	);
}
